# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='logging',
            field=models.BooleanField(default=True),
        ),
    ]
